Unexpected error: <type 'exceptions.ValueError'>
